%YAML 1.2
---

name: '192x10-expand'

dataset:
    # paths of training chunks to include
    train_path: 'data/v3/train/*.gz'
    test_path: 'data/v3/test/*.gz'

    # one of {'fixed', 'fixed_strict', 'every'}
    # 'fixed' samples a fixed number of unique positions per game, but allows for fewer if the game is too short
    # 'fixed_strict' always samples a fixed number of positions per game, but may contain duplicate positions
    # 'every' samples positions with some downsampling rate, so longer games are more likely to be sampled from
    # sample_argument specifies the positions per game for the 'fixed' and 'fixed_strict', and the downsampling rate for 'every'
    sample_method: 'subsample'
    sample_argument: 32

    # number of sampled positions to store in the shufflebuffer
    shufflebuffer_size: 250_000

training:
    total_steps: 200_000
    batch_size: 1024
    batch_splits: 1

    lr:
        # warmup
        - type: linear
          steps: 100
          start: 0.0
          end: 0.1
        # stepped lr
        - type: constant
          steps: 79_900
          at: 0.1
        - type: constant
          steps: 60_000
          at: 0.01
        - type: constant
          steps: 40_000
          at: 0.001
        - type: constant
          steps: 20_000
          at: 0.0001
    policy_weight: 1.0
    value_weight: 1.0
    reg_weight: 1.e-4

    max_gradient_norm: 9999

    checkpoint_every: 10000
    checkpoint_directory: 'checkpoints'

    swa_every: 10
    swa_momentum: 0.99

model:
    residual_channels: 192
    residual_blocks: 10
    policy_channels: 128
    se_ratio: 8

logging:
    directory: 'runs'
    train_every: 100
    test_steps: 25
    test_every: 500
    weight_histogram_every: 1000
    gradient_ratio_every: 100
