%YAML 1.2
---

name: '128x10-baseline'

dataset:
    train_path: 'data/v3/train/*'
    test_path: 'data/v3/test/*'

training:
    total_steps: 200_000
    batch_size: 1024
    batch_splits: 1

    shufflebuffer_size: 1_000_000
    positions_per_game: 4

    lr:
        # warmup
        - type: linear
          steps: 100
          start: 0.0
          end: 0.1
        # stepped lr
        - type: constant
          steps: 79_900
          at: 0.1
        - type: constant
          steps: 60_000
          at: 0.01
        - type: constant
          steps: 40_000
          at: 0.001
        - type: constant
          steps: 20_000
          at: 0.0001
    policy_weight: 1.0
    value_weight: 1.0
    reg_weight: 1.e-4

    max_gradient_norm: 9999

    checkpoint_every: 10000
    checkpoint_directory: 'checkpoints'

model:
    residual_channels: 128
    residual_blocks: 10
    policy_channels: 80
    se_ratio: 4

logging:
    directory: 'runs'
    test_steps: 50
    test_every: 1000
