%YAML 1.2
---

name: 'test'

dataset:
    train_path: 'data/v3/train/*'
    test_path: 'data/v3/test/*'

training:
    total_steps: 200_000
    batch_size: 2048
    batch_splits: 4

    lr:
        # warmup
        - type: linear
          steps: 10
          start: 0.0
          end: 0.1
        # stepped lr
        - type: constant
          steps: 20
          at: 0.1
        - type: constant
          steps: 20
          at: 0.01
        - type: constant
          steps: 20
          at: 0.001
    policy_weight: 1.0
    value_weight: 1.0
    reg_weight: 1.e-4

    max_gradient_norm: 2

    checkpoint_every: 1000
    checkpoint_directory: 'checkpoints'

model:
    residual_channels: 256
    residual_blocks: 20
    policy_channels: 80
    se_ratio: 4

logging:
    directory: 'runs'
    test_steps: 100
    test_every: 100
